server:
  port: 44444
  ssl:
    key-store: classpath:certificate/keystore.p12
    key-store-password: 123456789
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  devtools.restart.enabled: true  #设置开启热部署
  freemarker.cache: false     #页面不加载缓存，修改即时生效，生产时改为true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 15
    jedis.pool:
      max-active: 10
      max-idle: 8
      min-idle: 2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

logging.level:
  org: DEBUG
  com.nephew: DEBUG

mybatis:
  mapper-locations: classpath:mysql/*.xml

swagger:
  enabled: true
